# Generated by Django 4.0.4 on 2023-02-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('GH', 'GHOST'), ('EL', 'ELECTRIC'), ('WA', 'WATER'), ('ST', 'STEEL'), ('FA', 'FAIRY'), ('GR', 'GRASS')], default='WATER', max_length=250),
        ),
    ]
