# Generated by Django 4.0.4 on 2023-02-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('FA', 'FAIRY'), ('GH', 'GHOST'), ('GR', 'GRASS'), ('EL', 'ELECTRIC'), ('WA', 'WATER'), ('ST', 'STEEL')], default='WA', max_length=250),
        ),
    ]
