# Generated by Django 4.0.4 on 2023-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name_ar',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_fr',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('EL', 'ELECTRIC'), ('ST', 'STEEL'), ('WA', 'WATER'), ('GR', 'GRASS'), ('FA', 'FAIRY'), ('GH', 'GHOST')], default='WA', max_length=250),
        ),
    ]
