# Generated by Django 4.0.4 on 2023-02-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0007_alter_pokemon_name_ar_alter_pokemon_name_fr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name_ar',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_fr',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name_jp',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
